Tutorial Source: https://www.dataquest.io/blog/sql-basics/

In [1]:
import sqlite3
import pandas as pd

In [2]:
db = sqlite3.connect('hubway.db')

In [3]:
# cursor = db.cursor()
# cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
# print(cursor.fetchall())

In [4]:
def run_query(query):
    return pd.read_sql_query(query, db)

In [5]:
trips = run_query("SELECT * FROM trips")
trips

DatabaseError: Execution failed on sql 'SELECT * FROM trips': no such table: trips

In [36]:
stations = run_query("SELECT * FROM stations")
stations

,id,station,municipality,lat,lng
0,3,Colleges of the Fenway,Boston,42.340021,-71.100812
1,4,Tremont St. at Berkeley St.,Boston,42.345392,-71.069616
2,5,Northeastern U / North Parking Lot,Boston,42.341814,-71.090179
3,6,Cambridge St. at Joy St.,Boston,42.361284999999995,-71.06514
4,7,Fan Pier,Boston,42.353412,-71.044624
5,8,Union Square - Brighton Ave. at Cambridge St.,Boston,42.353334000000004,-71.137313
6,9,Agganis Arena - 925 Comm Ave.,Boston,42.351313,-71.116174
7,10,B.U. Central - 725 Comm. Ave.,Boston,42.350075,-71.105884
8,11,Longwood Ave / Binney St,Boston,42.338629,-71.1065
9,12,Ruggles Station / Columbus Ave.,Boston,42.335910999999996,-71.08849599999999
10,13,Boston Medical Center - 721 Mass. Ave.,Boston,42.334057,-71.07403000000001
11,14,HMS / HSPH - Ave. Louis Pasteur at Longwood Ave.,Boston,42.337171000000005,-71.102797
12,15,Harvard Real Estate - Brighton Mills - 370 Wes...,Boston,42.361667,-71.13802
13,16,Back Bay / South End Station,Boston,42.347433,-71.076163
14,17,Harvard University Housing - 111 Western Ave. ...,Boston,42.365074,-71.11958100000001
15,18,Harvard Real Estate - 219 Western Ave. at Nort...,Boston,42.36337,-71.129791
16,19,Buswell Park,Boston,42.347527,-71.105828
17,20,Aquarium Station - 200 Atlantic Ave.,Boston,42.359770000000005,-71.051601
18,21,Prudential Center / Belvidere,Boston,42.345959,-71.082578
19,22,South Station - 700 Atlantic Ave.,Boston,42.352175,-71.055547
20,23,Mayor Thomas M. Menino - Government Center,Boston,42.359677000000005,-71.059364
21,24,Seaport Square - Seaport Blvd. at Boston Wharf,Boston,42.351821,-71.045461
22,25,Tremont St / W Newton St,Boston,42.341332,-71.076847
23,26,Washington St. at Waltham St.,Boston,42.341522,-71.068922
24,27,Roxbury Crossing Station,Boston,42.331567,-71.094734
25,29,Innovation Lab - 125 Western Ave. at Batten Way,Boston,42.363732,-71.124565
26,30,Brigham Cir / Huntington Ave,Boston,42.334073,-71.105221
27,31,Seaport Hotel,Boston,42.348833,-71.041747
28,32,Landmark Centre,Boston,42.343911999999996,-71.102221
29,33,Kenmore Sq / Comm Ave,Boston,42.349046,-71.09683100000001
...,...,...,...,...,...
112,116,Charles St at Beacon St,Boston,42.356052000000005,-71.069849
113,117,Milk St at India St,Boston,42.358508,-71.052984
114,118,Hayes Square at Vine St.,Boston,42.377022,-71.056605
115,119,New Balance Store - Boylston at Dartmouth,Boston,42.350413,-71.07655
116,120,JP Monument - South St at Centre St,Boston,42.309467,-71.115645
117,121,JP Centre - Centre Street at Myrtle Street,Boston,42.31309,-71.114175
118,122,Hyde Square at Barbara St,Boston,42.320997999999996,-71.110833
119,123,Egleston Square at Columbus Ave,Boston,42.315692,-71.09863399999999
120,124,Green St T,Boston,42.310579,-71.107341
121,125,Jackson Square T at Centre St,Boston,42.322913,-71.100164
122,126,Washington Square at Washington St. / Beacon St.,Brookline,42.339335,-71.13493000000001
123,127,JFK Crossing at Harvard St. / Thorndike St.,Brookline,42.346563,-71.128374
124,128,Kendall T at Main St,Cambridge,42.362457,-71.08497
125,129,Harvard University River Houses / Plympton St ...,Cambridge,42.369832,-71.118201
126,130,Harvard University Gund Hall at Quincy St / Ki...,Cambridge,42.376369,-71.114025
127,131,Lower Cambridgeport at Magazine St/Riverside Rd,Cambridge,42.356953999999995,-71.113687
128,132,Harvard University / SEAS Cruft-Pierce Halls a...,Cambridge,42.377945000000004,-71.116865
129,133,Harvard University Radcliffe Quadrangle at She...,Cambridge,42.380287,-71.125107
130,134,Mass Ave / Linear Park,Cambridge,42.397828000000004,-71.130516
131,135,359 Broadway - Broadway at Fayette Street,Cambridge,42.370803,-71.104412
132,136,Biogen Idec - Binney St / Sixth St,Cambridge,42.366095,-71.086388
133,137,Porter Square Station,Cambridge,42.387995000000004,-71.119084
134,138,Wilson Square,Somerville,42.385582,-71.113341
135,139,Davis Square,Somerville,42.396969,-71.123024
136,140,Ball Square,Somerville,42.400146,-71.112708
137,141,Powder House Circle,Somerville,42.400877,-71.116772
138,142,Packard Ave / Powderhouse Blvd,Somerville,42.40449,-71.123413
139,143,Somerville Hospital at Highland Ave / Crocker St,Somerville,42.39082,-71.10942
140,144,Teele Square at 239 Holland St,Somerville,42.402763,-71.126908
141,145,Summer St at Cutter St,Somerville,42.394002,-71.120406\n